### ISSUE TITLE
Similar Project I'm Working On

### ISSUE THREAD

**Issue by zicklag** [irrustible/tingle#1]
Hey @jjl I found your project from your link in the `piper` issue about channels and noticed that it's kind of along the lines of the [maxim](https://github.com/katharostech/maxim) project that I'm working on ( in my free time when I can ).

It seems like we have similar goals and I'm currently looking into porting maxim to use smol as an executor and try to remove the built-in executor and convert some of the threading to tasks maybe.

Anyway, just curious if you wanted to check it out or collaborate on it. I'm just pursuing it rather casually at the moment, but I could use someone to bounce ideas off of.

**Comment by jjl** [comment]
I had a quick scan, and I think we have slightly different goals. It's not the actors I care about (see actix for why that's a bad idea :D), I just want to add some reliability back into futures.

So we kinda have a mailbox, but it's really only used for control messages because you can create new channels for everything else. We don't have selective receive because we don't need it. I'd rather we didn't even need the control messages but I've failed to get rid of them all so far.

For us it's all about the links (which we call tangles, after quantum entanglement). Those are the basis on which we can build things like supervision. I had a look at bastion and it was way too complex, but the joy of erlang has always been the simplicity, the way that from links we can derive all the other things quite neatly is why I've pursued a new library. I think there is a simpler way to get reliability and I'm here to prove it, albeit relatively casually.

Locally, I'm currently depending on a [patched piper](https://github.com/stjepang/piper/issues/2) which makes me not want to push what I'm working on until that issue is resolved one way or another.

We're in #irresponsible on freenode if you want to bounce ideas.

**Comment by zicklag** [comment]
Cool. Anyway, I like the sound of your ideas, though I haven't looked into them very deeply. I'll be watching this repo, albeit casually. ;)

I really like async, and I'm trying to find the foundation for which I build most of our future projects at @katharostech. Right now that's what I'm trying to build with Maxim. I had a look at Bastion too, but it was ***so*** verbose to accomplish stuff that I was able to do with Maxim in just a very short bit of code. Right now we're definitely leaning towards the actor model.

Reliability is a big concern because @katharostech is thinking of building a system orchestrator, so I'll be interested to see how tingle evolves even if it stays in the realm of experimental. :+1:

**Comment by jjl** [comment]
At some point, I'm going to declare that it's ready and start deploying it, I just don't think using it in production's a good idea before I've even executed the code ;)

**Comment by zicklag** [comment]
Don't *worry* I'm just going to *look at it*. :wink:
